"""Human-readable audit report for a generation (bound into the export bundle).

Renders the full :class:`~datadoom.engine.reports.ReportBundle` — compliance, the
per-column guide (stats + data-quality issues + ML advice), injected failures,
causal truth, difficulty, and the determinism record — into a single Markdown
document, ``audit_report.md``, opened with a clickable **table of contents** so a
reader can jump straight to a section (or a specific column). It ships alongside
the data, ``metadata.json`` and the locked ``spec.resolved.yaml`` so a downloaded
bundle is self-describing.

Pure, deterministic, **timestamp-free** (invariant #6): the same
``(spec_hash, seed)`` renders byte-identical Markdown.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .reports import ReportBundle
    from .spec.models import Spec

_SEVERITY_MARK = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "⚪"}


def _slug(text: str) -> str:
    """GitHub-style heading anchor: lowercase, drop punctuation, spaces → hyphens.

    Matches the id common Markdown renderers (GitHub, VS Code) derive from a
    heading, so the table-of-contents links resolve. Headings in this document
    are kept free of decorative characters so the mapping stays unambiguous.
    """
    s = text.strip().lower().replace("`", "")
    s = re.sub(r"[^\w\s-]", "", s)  # keep word chars, whitespace, hyphens
    return s.replace(" ", "-")


def _fmt(x: Any) -> str:
    """Compact, stable formatting for a number (or pass-through for non-numbers)."""
    if x is None:
        return "—"
    if isinstance(x, bool):
        return str(x)
    if isinstance(x, int):
        return str(x)
    if isinstance(x, float):
        if x != x:  # NaN
            return "—"
        if abs(x) >= 1e5 or (x != 0 and abs(x) < 1e-3):
            return f"{x:.3e}"
        return f"{x:.4g}"
    return str(x)


def _pct(x: float | None) -> str:
    return "—" if x is None else f"{x * 100:.1f}%"


def render_audit_markdown(
    spec: Spec, report: ReportBundle, *, package_version: str | None = None
) -> str:
    """Render the audit report for ``report`` as a Markdown string."""
    r = report.to_dict()
    det = r.get("determinism") or {}
    dist = r.get("distribution")
    profile = r.get("profile")
    failures = r.get("failures")
    truth = r.get("causal_truth")
    difficulty = r.get("difficulty")

    lines: list[str] = []
    w = lines.append

    # --- title -------------------------------------------------------------------
    w(f"# DataDoom Audit Report — {spec.name}")
    w("")
    if spec.description:
        w(f"_{spec.description}_")
        w("")
    w("> Regenerate byte-identical data from the locked `spec.resolved.yaml` in this")
    w("> bundle. This report is deterministic — no timestamps or ambient state.")
    w("")

    # --- table of contents -------------------------------------------------------
    # (title, present?) — only list sections that are actually rendered.
    toc: list[tuple[str, bool]] = [
        ("Overview", True),
        ("Distribution compliance", bool(dist and dist.get("features"))),
        ("Column guide", bool(profile and profile.get("columns"))),
        ("Injected failures", bool(failures and failures.get("modes"))),
        ("Causal truth", bool(truth and truth.get("edges"))),
        ("Difficulty calibration", bool(difficulty)),
        ("Determinism", bool(det.get("artifact_checksums"))),
    ]
    w("## Contents")
    w("")
    for title, present in toc:
        if not present:
            continue
        w(f"- [{title}](#{_slug(title)})")
        if title == "Column guide" and profile:
            for col in profile["columns"]:
                n_issues = len(col.get("issues") or [])
                suffix = f" — {n_issues} issue{'s' if n_issues != 1 else ''}" if n_issues else ""
                w(f"  - [{col['name']}](#{_slug(col['name'])}){suffix}")
    w("")

    # --- overview ----------------------------------------------------------------
    w("## Overview")
    w("")
    w("| Field | Value |")
    w("|---|---|")
    w(f"| Spec hash | `{det.get('spec_hash', '—')}` |")
    w(f"| Seed | `{det.get('seed', '—')}` |")
    w(f"| Rows | {spec.rows} |")
    w(f"| Features (declared) | {len(spec.features)} |")
    w(f"| datadoom_version | {spec.datadoom_version} |")
    if package_version:
        w(f"| Engine version | {package_version} |")
    score = r.get("compliance_score")
    if score is not None:
        w(f"| Compliance score | {_pct(score)} |")
    w("")

    _compliance(w, dist)
    _column_guide(w, profile)
    _failures(w, failures)
    _causal(w, truth)
    _difficulty(w, difficulty)
    _determinism(w, det)

    w("---")
    w("_Generated by DataDoom — controllable, reproducible synthetic data._")
    w("")
    return "\n".join(lines)


def _compliance(w: Any, dist: dict[str, Any] | None) -> None:
    if not dist or not dist.get("features"):
        return
    w("## Distribution compliance")
    w("")
    w("Honest fit of each realized column against its requested distribution (KS or")
    w("chi-square goodness-of-fit). Parameters are never refit to the sample.")
    w("")
    w("| Feature | Distribution | Emp. mean | Emp. std | Clamped | p-value | Verdict |")
    w("|---|---|---|---|---|---|---|")
    for c in dist["features"]:
        emp = c.get("empirical") or {}
        applicable = c.get("applicable", True)
        verdict = "n/a" if not applicable else ("pass" if c.get("passed") else "review")
        w(
            f"| {c.get('feature')} | {c.get('dist')} | {_fmt(emp.get('mean'))} | "
            f"{_fmt(emp.get('std'))} | {_pct(c.get('clamped_fraction'))} | "
            f"{_fmt(c.get('p_value')) if applicable else '—'} | {verdict} |"
        )
    w("")


def _column_guide(w: Any, profile: dict[str, Any] | None) -> None:
    if not profile or not profile.get("columns"):
        return
    s = profile.get("summary") or {}
    w("## Column guide")
    w("")
    w(
        f"{s.get('n_columns', 0)} columns · {s.get('columns_with_issues', 0)} with "
        f"data-quality issues · {s.get('critical_issues', 0)} critical · "
        f"{s.get('high_issues', 0)} high severity."
    )
    if s.get("label"):
        w("")
        w(f"Detected target column: **{s['label']}**.")
    w("")
    for col in profile["columns"]:
        # Heading is the bare column name so its anchor is stable for the TOC; the
        # role/type/derivation goes on the line below.
        w(f"### {col['name']}")
        meta = f"_{col.get('role', 'feature')} · {col.get('feature_type')} ({col.get('dtype')})_"
        parents = col.get("parents") or []
        if parents:
            meta += f" · _derived from: {', '.join(parents)}_"
        w(meta)
        w("")
        bits = [
            f"rows {col.get('count')}",
            f"missing {_pct(col.get('missing_pct'))}",
            f"unique {col.get('unique')}",
        ]
        stats = col.get("stats")
        if stats:
            bits += [
                f"mean {_fmt(stats.get('mean'))}",
                f"std {_fmt(stats.get('std'))}",
                f"min {_fmt(stats.get('min'))}",
                f"median {_fmt(stats.get('median'))}",
                f"max {_fmt(stats.get('max'))}",
            ]
        imb = col.get("imbalance")
        if imb:
            bits.append(f"balance {_pct(imb.get('majority_pct'))}/{_pct(imb.get('minority_pct'))}")
        inj = col.get("injected")
        if inj and inj.get("missing_pct"):
            bits.append(f"missing after injection {_pct(inj.get('missing_pct'))}")
        w("- " + " · ".join(bits))

        cats = col.get("categories")
        if cats:
            preview = ", ".join(f"{c['value']} {_pct(c['pct'])}" for c in cats[:6])
            w(f"- classes: {preview}")

        for issue in col.get("issues") or []:
            mark = _SEVERITY_MARK.get(issue.get("severity", "medium"), "•")
            w("")
            w(f"- {mark} **{issue.get('title')}** ({issue.get('severity')}) — {issue.get('magnitude')}")
            w(f"  - {issue.get('explanation')}")
            w(f"  - **How to handle it:** {issue.get('recommendation')}")
            for t in issue.get("techniques") or []:
                w(f"    - {t}")
        w("")


def _failures(w: Any, failures: dict[str, Any] | None) -> None:
    if not failures or not failures.get("modes"):
        return
    w("## Injected failures")
    w("")
    w(f"{failures.get('count', 0)} corruption(s) applied to the injected variant.")
    w("")
    for m in failures["modes"]:
        target = m.get("column") or m.get("into") or ", ".join((m.get("nullified_fraction") or {}).keys())
        w(f"- **{m.get('type')}** → `{target}`")
        for k, v in m.items():
            if k in ("index", "type", "mechanism"):
                continue
            w(f"  - {k}: {_fmt(v) if isinstance(v, (int, float)) else v}")
    w("")


def _causal(w: Any, truth: dict[str, Any] | None) -> None:
    if not truth or not truth.get("edges"):
        return
    w("## Causal truth")
    w("")
    w("The true generating graph (structural equations). Edges into an intervened")
    w("node are detached (`active: false`).")
    w("")
    w("| From | To | Function | Active |")
    w("|---|---|---|---|")
    for e in truth["edges"]:
        w(f"| {e.get('from')} | {e.get('to')} | {e.get('fn')} | {e.get('active', True)} |")
    interventions = truth.get("interventions") or {}
    if interventions:
        w("")
        w("Interventions: " + ", ".join(f"do({k}={_fmt(v)})" for k, v in interventions.items()))
    w("")


def _difficulty(w: Any, diff: dict[str, Any] | None) -> None:
    if not diff:
        return
    target = diff.get("target") or {}
    band = target.get("band") or [None, None]
    w("## Difficulty calibration")
    w("")
    w(
        f"Achieved **{_fmt(diff.get('achieved_metric'))} "
        f"{str(diff.get('metric_name', '')).upper()}** against target band "
        f"{_fmt(band[0])}–{_fmt(band[1])} "
        f"({'in band' if diff.get('band_met') else 'closest reached'}) "
        f"in {diff.get('iterations', 0)} iteration(s)."
    )
    w("")


def _determinism(w: Any, det: dict[str, Any]) -> None:
    checks = det.get("artifact_checksums") or {}
    if not checks:
        return
    w("## Determinism")
    w("")
    w("SHA-256 checksums of the data artifacts — the same `(spec_hash, seed)`")
    w("reproduces these byte-for-byte.")
    w("")
    w("| File | Checksum |")
    w("|---|---|")
    for name, digest in checks.items():
        w(f"| `{name}` | `{digest}` |")
    w("")
