"""Audit report — the human-readable run summary bound into the export bundle.

Asserts the report is written + registered as a tracked artifact, reflects the
real report sections (compliance, the column guide, injected failures), and is
deterministic/timestamp-free so the same ``(spec_hash, seed)`` renders identical
Markdown (invariant #6).
"""

from __future__ import annotations

import pytest

from datadoom.engine import generate, load_spec, parse_spec
from datadoom.engine.audit import render_audit_markdown

FAILURE_SPEC = "examples/failure-fraud.datadoom.yaml"
SEED = 42


@pytest.fixture(scope="module")
def run(tmp_path_factory):
    out = tmp_path_factory.mktemp("audit")
    return generate(load_spec(FAILURE_SPEC), seed=SEED, out_dir=out)


def test_audit_report_is_written_and_registered(run) -> None:
    audit = next((a for a in run.artifacts if a.version == "audit"), None)
    assert audit is not None
    assert audit.path == "audit_report.md" and audit.format == "md"
    assert len(audit.checksum_sha256) == 64
    assert (run.out_dir is not None) and (__import__("pathlib").Path(run.out_dir) / "audit_report.md").exists()


def test_audit_report_contains_key_sections(run) -> None:
    md = render_audit_markdown(load_spec(FAILURE_SPEC), run.report, package_version="x")
    assert "# DataDoom Audit Report" in md
    assert "## Distribution compliance" in md
    assert "## Column guide" in md  # the new results
    assert "## Injected failures" in md
    assert "How to handle it" in md  # ML advice is present
    assert "Target leakage" in md  # leakage issue surfaced
    assert run.spec_hash in md  # reproducibility anchor


def test_audit_report_has_navigable_toc(run) -> None:
    md = render_audit_markdown(load_spec(FAILURE_SPEC), run.report, package_version="x")
    assert "## Contents" in md
    # Every TOC anchor link must resolve to a heading slug in the document.
    import re

    headings = {
        re.sub(r"[^\w\s-]", "", h.strip().lower().replace("`", "")).replace(" ", "-")
        for h in re.findall(r"^#+\s+(.*)$", md, flags=re.M)
    }
    anchors = re.findall(r"\]\(#([\w-]+)\)", md)
    assert anchors  # the TOC produced links
    assert all(a in headings for a in anchors)  # …and each resolves
    # Per-column entries are present (a column the reader may jump to).
    assert "](#income)" in md


def test_audit_report_is_deterministic_and_timestamp_free() -> None:
    spec = load_spec(FAILURE_SPEC)
    a = render_audit_markdown(spec, generate(spec, seed=SEED).report, package_version="v")
    b = render_audit_markdown(spec, generate(spec, seed=SEED).report, package_version="v")
    assert a == b
    # No wall-clock leakage: the report must not embed a date/time.
    assert "202" not in a.replace(spec.spec_hash(), "") or "Generated by DataDoom" in a


def test_audit_report_handles_minimal_spec(tmp_path) -> None:
    spec = parse_spec(
        {
            "datadoom_version": "1",
            "name": "minimal",
            "rows": 50,
            "features": {"x": {"type": "numeric", "dist": "normal", "params": {"mean": 0, "std": 1}}},
        }
    )
    generate(spec, seed=1, out_dir=tmp_path)
    md = (tmp_path / "audit_report.md").read_text(encoding="utf-8")
    assert "# DataDoom Audit Report — minimal" in md
    assert "## Injected failures" not in md  # no failures → section omitted
